baseURL: "https://votre-domaine.com"
languageCode: "fr-FR"
title: "TechVeille - Blog IA & Tech"
#theme: "techveille"

params:
  author: "Votre Nom"
  description: "Blog spécialisé en Intelligence Artificielle, Technologies et Systèmes. Articles quotidiens sur les dernières innovations tech."
  keywords: ["IA", "Intelligence Artificielle", "Tech", "Informatique", "Base de données", "Systèmes", "DevOps", "Machine Learning"]
  
  # SEO et réseaux sociaux
  twitter: "@votre_twitter"
  github: "votre-github"
  linkedin: "votre-linkedin"
  
  # Analytics (décommentez si nécessaire)
  # googleAnalytics: "G-XXXXXXXXXX"
  
  # Monétisation
  patreon: "votre-patreon"
  tipeee: "votre-tipeee"
  
  # Newsletter
  newsletter:
    enabled: true
    action: "https://votre-service-newsletter.com/subscribe"
    
  # Commentaires (optionnel)
  comments:
    enabled: false
    # disqus: "votre-disqus-shortname"

# Menu de navigation
menu:
  main:
    - name: "Accueil"
      url: "/"
      weight: 10
    - name: "Articles"
      url: "/posts/"
      weight: 20
    - name: "IA"
      url: "/categories/ia/"
      weight: 30
    - name: "Tech"
      url: "/categories/tech/"
      weight: 40
    - name: "Systèmes"
      url: "/categories/systemes/"
      weight: 50
    - name: "À propos"
      url: "/about/"
      weight: 60

# Configuration du markup
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: "github-dark"
    lineNos: true
    codeFences: true
    guessSyntax: true

# Formats de sortie
outputs:
  home: ["HTML", "RSS", "JSON"]
  page: ["HTML"]
  section: ["HTML", "RSS"]

# Taxonomies
taxonomies:
  category: "categories"
  tag: "tags"

# Pagination
pagination:
  pagerSize: 10

# Sécurité
security:
  exec:
    allow: ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
  funcs:
    getenv: ['^HUGO_']