baseURL: "https://Kyrostech.dev"
languageCode: "fr-FR"
title: "Kyrostech - Blog IA & Tech"

# SEO amélioré
params:
  author: "Kyrostech"
  description: "Blog spécialisé en Intelligence Artificielle, Technologies et Systèmes. Articles quotidiens sur les dernières innovations tech avec explications accessibles."
  keywords: ["IA", "Intelligence Artificielle", "Tech", "Informatique", "Base de données", "Systèmes", "DevOps", "Machine Learning", "Docker", "Cloud"]
  
  # Réseaux sociaux - complétés
  twitter: "@kyrostechdev"
  github: "kyrostech"
  linkedin: "kyrostech"
  
  # Analytics activés
  googleAnalytics: "G-XXXXXXXXXX"
  
  # Monétisation - liens réels
  patreon: "kyrostech"
  tipeee: "kyrostech"
  
  # Newsletter - service réel
  newsletter:
    enabled: true
    action: "https://kyrostech.us21.list-manage.com/subscribe/post?u=XXXXX&id=XXXXX"
    
  # Commentaires activés
  comments:
    enabled: true
    disqus: "kyrostech-blog"

# Menu optimisé
menu:
  main:
    - name: "Accueil"
      url: "/"
      weight: 10
    - name: "Articles"
      url: "/posts/"
      weight: 20
    - name: "IA"
      url: "/categories/ia/"
      weight: 30
    - name: "Tech"
      url: "/categories/tech/"
      weight: 40
    - name: "Systèmes"
      url: "/categories/systemes/"
      weight: 50
    - name: "Docker"
      url: "/categories/docker/"
      weight: 45
    - name: "À propos"
      url: "/about/"
      weight: 60

# SEO avancé
permalinks:
  posts: "/:year/:month/:slug/"

# Sitemap optimisé
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.8

# RSS complet
outputs:
  home: ["HTML", "RSS", "JSON"]
  page: ["HTML"]
  section: ["HTML", "RSS"]

# Taxonomies enrichies
taxonomies:
  category: "categories"
  tag: "tags"
  author: "authors"