baseURL: "https://kyrostech.dev"
languageCode: "fr-FR"
title: "Kyrostech - Blog IA & Tech"
enableRobotsTXT: true  # Ajout pour générer robots.txt automatiquement

minify:
  disableXML: false  # Garde la minification des fichiers XML (comme sitemap.xml)
  minifyOutput: true  # Active la minification des HTML, CSS, JS, etc.
  
# SEO amélioré
params:
  author: "Kyrostech"
  description: "Blog spécialisé en Intelligence Artificielle, Technologies et Systèmes. Articles quotidiens sur les dernières innovations tech avec explications accessibles."
  keywords: ["IA", "Intelligence Artificielle", "Tech", "Informatique", "Base de données", "Systèmes", "DevOps", "Machine Learning", "Docker", "Cloud"]
  images: ["/images/logo.png"]  # Ajout pour Open Graph, remplace par ton logo ou image par défaut
  copyright: "© 2025 Kyrostech - Tous droits réservés"  # Ajout pour le pied de page

  # Réseaux sociaux - complétés
  twitter: "@kyrostechdev"
  github: "kyrostech"
  linkedin: "kyrostech"

  # Analytics activés
  googleAnalytics: "G-XXXXXXXXXX"

  # Monétisation - liens réels
  patreon: "kyrostech"
  tipeee: "kyrostech"

  # Newsletter - service réel
  newsletter:
    enabled: true
    action: "https://kyrostech.us21.list-manage.com/subscribe/post?u=XXXXX&id=XXXXX"

  # Commentaires activés
  comments:
    enabled: true
    disqus: "kyrostech-blog"

# Menu optimisé et hiérarchisé
menu:
  main:
    - name: "Accueil"
      url: "/"
      weight: 10
    - name: "Articles"
      url: "/posts/"
      weight: 20
    - name: "Catégories"
      hasChildren: true  # Ajout pour un menu déroulant
      weight: 30
    - name: "IA"
      url: "/categories/ia/"
      weight: 10
    - name: "Tech"
      url: "/categories/tech/"
      weight: 20
    - name: "Systèmes"
      url: "/categories/systemes/"
      weight: 30
    - name: "Docker"
      url: "/categories/docker/"
      weight: 40
    - name: "À propos"
      url: "/about/"
      weight: 60

# SEO avancé
permalinks:
  posts: "/:slug/"

# Sitemap optimisé
sitemap:
  changefreq: "daily"
  filename: "sitemap.xml"
  priority: 0.8
  sitemapTaxonomies: true  # Ajout pour inclure les taxonomies

# RSS complet et SEO
outputs:
  home: ["HTML", "RSS", "JSON"]
  page: ["HTML", "RSS", "JSON"]  # Ajout RSS pour les pages individuelles
  section: ["HTML", "RSS"]

# Taxonomies enrichies
taxonomies:
  category: "categories"
  tag: "tags"
  author: "authors"

# Performance et minification
minify:
  disableXML: false  # Garde la minification XML
  minifyOutput: true  # Minifie HTML, CSS, JS générés

# Sécurité et headers HTTP
security:
  enableInlineScript: false  # Désactive les scripts inline pour la sécurité
  enableInlineStyle: false  # Désactive les styles inline

# Paramètres additionnels pour Hugo
build:
  writeStats: true  # Génère des stats pour débogage
  noChmod: true  # Optimise les permissions

# config.yaml
module:
  imports:
    - path: github.com/future-wd/hugo-seo
    - path: github.com/hugomods/images
    - path: github.com/hugomods/search
    - path: github.com/hugomods/pwa
    - path: github.com/hugomods/icons

params:
  seo:
    title: true
    meta: true
    og: true
    twitter: true
    jsonld:
      article: true
      breadcrumbs: true

  images:
    quality: 85
    webp: true
    lazy: true

  search:
    indexPaginate: 50
    fuseOptions:
      threshold: 0.3

  pwa:
    enable: true
    name: "Tech Blog"
    short_name: "Tech"
    theme_color: "#0057e7"

# Langues
languages:
  fr:
    languageName: "Français"
    weight: 1
    title: "Kyrostech - Blog IA & Tech"

# Markup (syntaxe YAML corrigée)
markup:
  goldmark:
    renderer:
      unsafe: false  # Désactive le rendu HTML non sécurisé